mysql:
  host: '37.187.71.101:3306'
  user: test
  password: test
  database: test
  table-prefix: 'hsc_'
power:
  regen-offline: false
  # Power regeneration per minute.
  per-minute: 0.2
  # Value of power which is set to player when he joins a server for the first time.
  start-value: 10.0
  max-value: 10.0
  min-value: -10.0
  loss-per-death: 5.0
  offline:
    loss-per-day: 5.0
    # Minimal value of power which can be set if player has been offline for a couple of days.
    loss-limit: 0.0
player:
  auto-leave:
    # This feature kick player from clan if he has been inactive for more than <hours_inactive>.
    enabled: true
    hours-inactive: 48.0
    # Period between task is executed (in hours).
    period: 12.0
  levels:
    1:
      name: '&7-'
      rate: 0.0
    2:
      name: 'Рекрут'
      rate: 0.05
    3:
      name: 'Боец'
      rate: 0.1
    4:
      name: 'Бывалый'
      rate: 0.2
    5:
      name: 'Гладиатор'
      rate: 0.5
    6:
      name: 'Чемпион'
      rate: 0.9
    7:
      name: 'Герой'
      rate: 1.2
    8:
      name: 'Легенда'
      rate: 1.5
    9:
      name: 'Повелитель'
      rate: 1.8
    10:
      name: 'Богоподобный'
      rate: 2.1
clan:
  home:
    # Minimal height where player can set his home. He will be unable to set it lower than this.
    min-height: 50.0
    respawn: true
  levels:
    1:
      name: '-'
      rate: 0.0
    2:
      name: 'Обыватель'
      rate: 0.05
    3:
      name: 'Топ Клан'
      rate: 1.0
pvp:
  # These potions are treated as harmful. It means that they will be blocked when attacker damages allies/friends with these ones.
  bad-potions:
  - BLINDNESS
  - CONFUSION
  - HARM
  - HUNGER
  - POISON
  - SLOW
  - SLOW_DIGGING
  - WEAKNESS
  - WITHER
claims:
  teleport-from:
    # If true - player will be able to teleport from enemy claims when owners are offline.
    offline: true
    # If true - player will be able to teleport from enemy claims when owner are online.
    online: false
    # If there are enemies within this distance (value) (inclusive) teleport will be denied.
    distance:
      enabled: true
      value: 32.0
  denied-worlds:
  - 'world_nether'
  deny:
    enderman-grief: true
    wither-grief: true
    # Explosion types: CREEPER, FIREBALL, WITHER, TNT, MINECART
    explosion:
      always:
      - CREEPER
      - FIREBALL
      - WITHER
      - MINECART
      offline:
      - TNT
    usage:
      # Usage of these items will be blocked whenever clan is offline or online.
      always:
      - LAVA_BUCKET
    # Usage of these items will be blocked when clan is offline.
      offline:
      - BUCKET
      - FIREBALL
      - WATER_BUCKET
      - FLINT_AND_STEEL
      # Usage of these items will be blocked for newbie (player whose clan role is the lowest in clan).
      newbie:
      - WATER_BUCKET
      - LAVA_BUCKET
      allie:
      - LAVA_BUCKET
      - WATER_BUCKET
      - BUCKET
      - FIREBALL
    interact:
      # Interaction with these items will be blocked whenever clan is offline or online.
      always:
      - WOODEN_DOOR
      - TRAP_DOOR
      - FENCE_GATE
      - DISPENSER
      - CHEST
      - FURNACE
      - BURNING_FURNACE
      - DIODE_BLOCK_OFF
      - DIODE_BLOCK_ON
      - JUKEBOX
      - BREWING_STAND
      - ENCHANTMENT_TABLE
      - CAULDRON
      - SOIL
      - BEACON
      - ANVIL
      - TRAPPED_CHEST
      - LOCKED_CHEST
      - DROPPER
      - HOPPER
      # Interaction with these items will be blocked when clan is online.
      offline:
      # Interaction with these items will be blocked when clan is online.
      newbie:
      - DISPENSER
      - CHEST
      - FURNACE
      - BURNING_FURNACE
      - JUKEBOX
      - BREWING_STAND
      - CAULDRON
      - SOIL
      - BEACON
      - TRAPPED_CHEST
      - LOCKED_CHEST
      - DROPPER
      - HOPPER
      allie:
      - DISPENSER
      - CHEST
      - FURNACE
      - BURNING_FURNACE
      - JUKEBOX
      - BREWING_STAND
      - CAULDRON
      - SOIL
      - BEACON
      - TRAPPED_CHEST
      - DROPPER
      - HOPPER
map:
  height: 7
  width: 28
performance:
  # Cache all players (when plugin tries to get player info from MySQL, it caches it so that future requests to this info will be faster)
  cache-on-request: false
  # Load players who is in a clan to cache on plugin load. By default, only online players are added to cache.
  cache-clan-players: true
  # Should player's cache be cleared when he leaves a server or not.
  cache-clear-on-leave: false
integration:
  # Integration with essentials homes (cooldown, delay, etc).
  essentials: true