mysql:
  host: '37.187.71.101:3306'
  user: test
  password: test
  database: test
  table-prefix: 'hsc_'
power:
  regen-offline: false
  # Power regeneration per minute.
  per-minute: 0.2
  # Value of power which is set to player when he joins a server for the first time.
  start-value: 0.0
  max-value: 10.0
  min-value: -10.0
  loss-per-death: 5.0
  offline:
    loss-per-day: 5.0
    # Minimal value of power which can be set if player has been offline for a couple of days.
    loss-limit: 0.0
clan:
  levels:
    medium:
      days: 1
    high:
      days: 2
performance:
  # Cache all players (when plugin tries to get player info from MySQL, it caches it so that future requests to this info will be faster)
  cache-all: true