name: HSClans
version: 0.3
main: ru.lexmint.HSClans
authors: [Lexmint]
# TODO Only for last loading to easily debug
softdepent: [Vault, HSJail, NoCheatPlus]
commands:
  factions:
    description: Базовая команда плагина.
    aliases: [f]
permissions:
#  hsclans.command.create: